type ProductDocument = {
	itemId: number;
	name: string;
	code: string;
	itemTypeId: number;
	description: string;
	brand: string;
	thumbnail: string;
	images: string[];
	status: number;
	price: string;
	amountOff: string;
	discount: any;
	numBuy: number;
	averageStar: number;
	tags: any;
	slug: string;
	createdBy: any;
	createdAt: string;
	updatedAt: string;
};
